[project]
name = "obvirm-whisperxx"
description = "WhisperCPP for ComfyUI - whisper.cpp with full CPP params, alignment, diarization"
version = "2.0.8"
license = {file = "LICENSE"}
dependencies = ["numpy","tqdm","requests","huggingface-hub","scipy","sherpa-onnx"]

[project.urls]
Repository = "https://github.com/obvirm/ComfyUI-WhisperCPP"
Documentation = "https://github.com/obvirm/ComfyUI-WhisperCPP/wiki"
"Bug Tracker" = "https://github.com/obvirm/ComfyUI-WhisperCPP/issues"

[tool.comfy]
PublisherId = "obvirm"
DisplayName = "ComfyUI-WhisperCPP"
Icon = ""
includes = []
